# FSR Autogenerated Content. DO NOT DELETE
from .custom_connector import CustomConnector
from connectors.core.connector import get_logger, ConnectorError


def health_check(config: dict):
    pass


def generic_api_call(config: dict, params: dict):
    pass


def do_something(config: dict, params: dict) -> dict:
    conn = CustomConnector()
    return conn.do_something(config, params)


def raise_error(config: dict, params: dict) -> dict:
    raise ConnectionError("this is an error!")
    conn = CustomConnector()
    return conn.raise_error(config, params)


supported_operations = {
    "generic_api_call": generic_api_call,
    "do_something": do_something,
    "raise_error": raise_error,
}
